---
- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: isucon
  tasks:
    - file: path=/home/isucon/.ssh state=directory owner=isucon mode=755
    - git:
        repo=https://github.com/isucon/isucon5-final.git
        dest=/home/isucon/isucon5-final
    - copy: src=../files/env.sh dest=/home/isucon/env.sh owner=isucon mode=755
    - name: ruby
      shell: PATH=/home/isucon/.local/ruby/bin:$PATH bundle install
      args:
        chdir: /home/isucon/isucon5-final/bench
    - name: java build
      shell: gradle compileJava
      args:
        chdir: /home/isucon/isucon5-final/bench
